// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Article struct {
	ID           string  `json:"id"`
	Title        *string `json:"title"`
	Link         *string `json:"link"`
	Description  *string `json:"description"`
	Content      *string `json:"content"`
	ImageUrl     *string `json:"image_url"`
	PubDate      *string `json:"pub_date"`
	Guid         *string `json:"guid"`
	SourceFeedID *string `json:"source_feed_id"`
	CreatedAt    string  `json:"created_at"`
}

type ArticleRead struct {
	UserID    string `json:"user_id"`
	ArticleID string `json:"article_id"`
	ReadAt    string `json:"read_at"`
}

type Category struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
}

type Feed struct {
	ID            string  `json:"id"`
	Url           string  `json:"url"`
	Title         *string `json:"title"`
	CustomTitle   *string `json:"custom_title"`
	Description   *string `json:"description"`
	Language      string  `json:"language"`
	UserID        string  `json:"user_id"`
	SourceFeedID  *string `json:"source_feed_id"`
	CategoryID    *string `json:"category_id"`
	LastFetchedAt *string `json:"last_fetched_at"`
	CreatedAt     string  `json:"created_at"`
}

type ImageCache struct {
	SourceUrl   string `json:"source_url"`
	ContentType string `json:"content_type"`
	Data        []byte `json:"data"`
	FetchedAt   string `json:"fetched_at"`
}

type PasswordResetToken struct {
	ID        string  `json:"id"`
	TokenHash string  `json:"token_hash"`
	UserID    string  `json:"user_id"`
	ExpiresAt string  `json:"expires_at"`
	UsedAt    *string `json:"used_at"`
	CreatedAt string  `json:"created_at"`
}

type RateLimitEntry struct {
	Key     string `json:"key"`
	Count   int64  `json:"count"`
	ResetAt string `json:"reset_at"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SmartFeed struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Query     string  `json:"query"`
	FeedID    *string `json:"feed_id"`
	UserID    string  `json:"user_id"`
	CreatedAt string  `json:"created_at"`
}

type SmartFeedFeed struct {
	SmartFeedID string `json:"smart_feed_id"`
	FeedID      string `json:"feed_id"`
}

type SourceFeed struct {
	ID            string  `json:"id"`
	Url           string  `json:"url"`
	Title         *string `json:"title"`
	Description   *string `json:"description"`
	Language      string  `json:"language"`
	LastFetchedAt *string `json:"last_fetched_at"`
	CreatedAt     string  `json:"created_at"`
}

type User struct {
	ID           string  `json:"id"`
	Name         *string `json:"name"`
	Email        string  `json:"email"`
	Password     *string `json:"password"`
	Role         string  `json:"role"`
	Banned       int64   `json:"banned"`
	BannedReason *string `json:"banned_reason"`
	CreatedAt    string  `json:"created_at"`
}

type UserPreference struct {
	UserID           string `json:"user_id"`
	Theme            string `json:"theme"`
	Design           string `json:"design"`
	CardStyle        string `json:"card_style"`
	Density          string `json:"density"`
	FontScale        string `json:"font_scale"`
	Background       string `json:"background"`
	FontFamily       string `json:"font_family"`
	AccentColor      string `json:"accent_color"`
	ShowImages       int64  `json:"show_images"`
	ShowSource       int64  `json:"show_source"`
	ShowDate         int64  `json:"show_date"`
	ShowDescription  int64  `json:"show_description"`
	ShowReadMore     int64  `json:"show_read_more"`
	DescriptionLines int64  `json:"description_lines"`
	UpdatedAt        string `json:"updated_at"`
}
