// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const countArticles = `-- name: CountArticles :one
SELECT count(*) FROM articles
`

func (q *Queries) CountArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticlesForSource = `-- name: CountArticlesForSource :one
SELECT count(*) FROM articles WHERE source_feed_id = ?
`

func (q *Queries) CountArticlesForSource(ctx context.Context, sourceFeedID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticlesForSource, sourceFeedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFeeds = `-- name: CountFeeds :one
SELECT count(*) FROM feeds
`

func (q *Queries) CountFeeds(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeeds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSourceFeeds = `-- name: CountSourceFeeds :one
SELECT count(*) FROM source_feeds
`

func (q *Queries) CountSourceFeeds(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSourceFeeds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, name, user_id) VALUES (?, ?, ?)
RETURNING id, name, user_id, created_at
`

type CreateCategoryParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.ID, arg.Name, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, url, title, description, language, user_id, source_feed_id, last_fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))
RETURNING id, url, title, description, language, user_id, source_feed_id, category_id, last_fetched_at, created_at
`

type CreateFeedParams struct {
	ID           string  `json:"id"`
	Url          string  `json:"url"`
	Title        *string `json:"title"`
	Description  *string `json:"description"`
	Language     string  `json:"language"`
	UserID       string  `json:"user_id"`
	SourceFeedID *string `json:"source_feed_id"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.Language,
		arg.UserID,
		arg.SourceFeedID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.UserID,
		&i.SourceFeedID,
		&i.CategoryID,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.UserID, arg.ExpiresAt)
	return err
}

const createSmartFeed = `-- name: CreateSmartFeed :one
INSERT INTO smart_feeds (id, name, query, feed_id, user_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, "query", feed_id, user_id, created_at
`

type CreateSmartFeedParams struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Query  string  `json:"query"`
	FeedID *string `json:"feed_id"`
	UserID string  `json:"user_id"`
}

func (q *Queries) CreateSmartFeed(ctx context.Context, arg CreateSmartFeedParams) (SmartFeed, error) {
	row := q.db.QueryRowContext(ctx, createSmartFeed,
		arg.ID,
		arg.Name,
		arg.Query,
		arg.FeedID,
		arg.UserID,
	)
	var i SmartFeed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.FeedID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password, role)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, email, password, role, banned, banned_reason, created_at
`

type CreateUserParams struct {
	ID       string  `json:"id"`
	Name     *string `json:"name"`
	Email    string  `json:"email"`
	Password *string `json:"password"`
	Role     string  `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Banned,
		&i.BannedReason,
		&i.CreatedAt,
	)
	return i, err
}

const createUserPreference = `-- name: CreateUserPreference :exec
INSERT INTO user_preferences (user_id) VALUES (?)
ON CONFLICT(user_id) DO NOTHING
`

func (q *Queries) CreateUserPreference(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, createUserPreference, userID)
	return err
}

const deleteCategoryForUser = `-- name: DeleteCategoryForUser :exec
DELETE FROM categories WHERE id = ? AND user_id = ?
`

type DeleteCategoryForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCategoryForUser(ctx context.Context, arg DeleteCategoryForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryForUser, arg.ID, arg.UserID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteFeedForUser = `-- name: DeleteFeedForUser :exec
DELETE FROM feeds WHERE id = ? AND user_id = ?
`

type DeleteFeedForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteFeedForUser(ctx context.Context, arg DeleteFeedForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedForUser, arg.ID, arg.UserID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	return err
}

const deleteSmartFeedForUser = `-- name: DeleteSmartFeedForUser :exec
DELETE FROM smart_feeds WHERE id = ? AND user_id = ?
`

type DeleteSmartFeedForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteSmartFeedForUser(ctx context.Context, arg DeleteSmartFeedForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteSmartFeedForUser, arg.ID, arg.UserID)
	return err
}

const getCachedImage = `-- name: GetCachedImage :one
SELECT content_type, data FROM image_cache WHERE source_url = ? LIMIT 1
`

type GetCachedImageRow struct {
	ContentType string `json:"content_type"`
	Data        []byte `json:"data"`
}

func (q *Queries) GetCachedImage(ctx context.Context, sourceUrl string) (GetCachedImageRow, error) {
	row := q.db.QueryRowContext(ctx, getCachedImage, sourceUrl)
	var i GetCachedImageRow
	err := row.Scan(&i.ContentType, &i.Data)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, user_id, created_at FROM categories WHERE id = ? LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedByID = `-- name: GetFeedByID :one
SELECT id, url, title, description, language, user_id, source_feed_id, category_id, last_fetched_at, created_at FROM feeds WHERE id = ? LIMIT 1
`

func (q *Queries) GetFeedByID(ctx context.Context, id string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.UserID,
		&i.SourceFeedID,
		&i.CategoryID,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRateLimit = `-- name: GetRateLimit :one
SELECT count, reset_at FROM rate_limit_entries WHERE key = ? LIMIT 1
`

type GetRateLimitRow struct {
	Count   int64  `json:"count"`
	ResetAt string `json:"reset_at"`
}

func (q *Queries) GetRateLimit(ctx context.Context, key string) (GetRateLimitRow, error) {
	row := q.db.QueryRowContext(ctx, getRateLimit, key)
	var i GetRateLimitRow
	err := row.Scan(&i.Count, &i.ResetAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, expires_at, created_at FROM sessions WHERE id = ? AND expires_at > datetime('now') LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ? LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSmartFeedByID = `-- name: GetSmartFeedByID :one
SELECT id, name, "query", feed_id, user_id, created_at FROM smart_feeds WHERE id = ? LIMIT 1
`

func (q *Queries) GetSmartFeedByID(ctx context.Context, id string) (SmartFeed, error) {
	row := q.db.QueryRowContext(ctx, getSmartFeedByID, id)
	var i SmartFeed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Query,
		&i.FeedID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceFeedByURL = `-- name: GetSourceFeedByURL :one
SELECT id, url, title, description, language, last_fetched_at, created_at FROM source_feeds WHERE url = ? LIMIT 1
`

func (q *Queries) GetSourceFeedByURL(ctx context.Context, url string) (SourceFeed, error) {
	row := q.db.QueryRowContext(ctx, getSourceFeedByURL, url)
	var i SourceFeed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, role, banned, banned_reason, created_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Banned,
		&i.BannedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password, role, banned, banned_reason, created_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.Banned,
		&i.BannedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getUserFeedByURL = `-- name: GetUserFeedByURL :one
SELECT id, url, title, description, language, user_id, source_feed_id, category_id, last_fetched_at, created_at FROM feeds WHERE user_id = ? AND url = ? LIMIT 1
`

type GetUserFeedByURLParams struct {
	UserID string `json:"user_id"`
	Url    string `json:"url"`
}

func (q *Queries) GetUserFeedByURL(ctx context.Context, arg GetUserFeedByURLParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getUserFeedByURL, arg.UserID, arg.Url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.UserID,
		&i.SourceFeedID,
		&i.CategoryID,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPreference = `-- name: GetUserPreference :one
SELECT user_id, theme, design, card_style, density, font_scale, accent_color, show_images, show_source, show_date, show_description, description_lines, updated_at FROM user_preferences WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetUserPreference(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreference, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.Design,
		&i.CardStyle,
		&i.Density,
		&i.FontScale,
		&i.AccentColor,
		&i.ShowImages,
		&i.ShowSource,
		&i.ShowDate,
		&i.ShowDescription,
		&i.DescriptionLines,
		&i.UpdatedAt,
	)
	return i, err
}

const insertArticle = `-- name: InsertArticle :exec
INSERT INTO articles (id, title, link, description, content, image_url, pub_date, guid, source_feed_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(source_feed_id, guid) DO NOTHING
`

type InsertArticleParams struct {
	ID           string  `json:"id"`
	Title        *string `json:"title"`
	Link         *string `json:"link"`
	Description  *string `json:"description"`
	Content      *string `json:"content"`
	ImageUrl     *string `json:"image_url"`
	PubDate      *string `json:"pub_date"`
	Guid         *string `json:"guid"`
	SourceFeedID *string `json:"source_feed_id"`
}

func (q *Queries) InsertArticle(ctx context.Context, arg InsertArticleParams) error {
	_, err := q.db.ExecContext(ctx, insertArticle,
		arg.ID,
		arg.Title,
		arg.Link,
		arg.Description,
		arg.Content,
		arg.ImageUrl,
		arg.PubDate,
		arg.Guid,
		arg.SourceFeedID,
	)
	return err
}

const listArticlesByLanguage = `-- name: ListArticlesByLanguage :many
SELECT a.id, a.title, a.link, a.description, a.content, a.image_url, a.pub_date, a.guid, a.source_feed_id, a.created_at FROM articles a
JOIN source_feeds sf ON sf.id = a.source_feed_id
WHERE sf.language = ?
ORDER BY a.pub_date DESC NULLS LAST, a.created_at DESC
LIMIT ? OFFSET ?
`

type ListArticlesByLanguageParams struct {
	Language string `json:"language"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) ListArticlesByLanguage(ctx context.Context, arg ListArticlesByLanguageParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByLanguage, arg.Language, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Link,
			&i.Description,
			&i.Content,
			&i.ImageUrl,
			&i.PubDate,
			&i.Guid,
			&i.SourceFeedID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesForUser = `-- name: ListArticlesForUser :many
SELECT DISTINCT a.id, a.title, a.link, a.description, a.content, a.image_url,
  a.pub_date, a.guid, a.source_feed_id, a.created_at,
  CASE WHEN EXISTS(
    SELECT 1 FROM article_reads ar WHERE ar.user_id = ? AND ar.article_id = a.id
  ) THEN 1 ELSE 0 END AS read
FROM articles a
JOIN feeds f ON f.source_feed_id = a.source_feed_id
WHERE f.user_id = ?
ORDER BY a.pub_date DESC NULLS LAST, a.created_at DESC
LIMIT ? OFFSET ?
`

type ListArticlesForUserParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

type ListArticlesForUserRow struct {
	ID           string  `json:"id"`
	Title        *string `json:"title"`
	Link         *string `json:"link"`
	Description  *string `json:"description"`
	Content      *string `json:"content"`
	ImageUrl     *string `json:"image_url"`
	PubDate      *string `json:"pub_date"`
	Guid         *string `json:"guid"`
	SourceFeedID *string `json:"source_feed_id"`
	CreatedAt    string  `json:"created_at"`
	Read         int64   `json:"read"`
}

func (q *Queries) ListArticlesForUser(ctx context.Context, arg ListArticlesForUserParams) ([]ListArticlesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesForUser,
		arg.UserID,
		arg.UserID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesForUserRow
	for rows.Next() {
		var i ListArticlesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Link,
			&i.Description,
			&i.Content,
			&i.ImageUrl,
			&i.PubDate,
			&i.Guid,
			&i.SourceFeedID,
			&i.CreatedAt,
			&i.Read,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesForUserByCategory = `-- name: ListArticlesForUserByCategory :many
SELECT DISTINCT a.id, a.title, a.link, a.description, a.content, a.image_url,
  a.pub_date, a.guid, a.source_feed_id, a.created_at,
  CASE WHEN EXISTS(
    SELECT 1 FROM article_reads ar WHERE ar.user_id = ? AND ar.article_id = a.id
  ) THEN 1 ELSE 0 END AS read
FROM articles a
JOIN feeds f ON f.source_feed_id = a.source_feed_id
WHERE f.user_id = ? AND f.category_id = ?
ORDER BY a.pub_date DESC NULLS LAST, a.created_at DESC
LIMIT ? OFFSET ?
`

type ListArticlesForUserByCategoryParams struct {
	UserID     string  `json:"user_id"`
	UserID_2   string  `json:"user_id_2"`
	CategoryID *string `json:"category_id"`
	Limit      int64   `json:"limit"`
	Offset     int64   `json:"offset"`
}

type ListArticlesForUserByCategoryRow struct {
	ID           string  `json:"id"`
	Title        *string `json:"title"`
	Link         *string `json:"link"`
	Description  *string `json:"description"`
	Content      *string `json:"content"`
	ImageUrl     *string `json:"image_url"`
	PubDate      *string `json:"pub_date"`
	Guid         *string `json:"guid"`
	SourceFeedID *string `json:"source_feed_id"`
	CreatedAt    string  `json:"created_at"`
	Read         int64   `json:"read"`
}

func (q *Queries) ListArticlesForUserByCategory(ctx context.Context, arg ListArticlesForUserByCategoryParams) ([]ListArticlesForUserByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesForUserByCategory,
		arg.UserID,
		arg.UserID_2,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesForUserByCategoryRow
	for rows.Next() {
		var i ListArticlesForUserByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Link,
			&i.Description,
			&i.Content,
			&i.ImageUrl,
			&i.PubDate,
			&i.Guid,
			&i.SourceFeedID,
			&i.CreatedAt,
			&i.Read,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesForUserBySmartFeed = `-- name: ListArticlesForUserBySmartFeed :many
SELECT DISTINCT a.id, a.title, a.link, a.description, a.content, a.image_url,
  a.pub_date, a.guid, a.source_feed_id, a.created_at,
  CASE WHEN EXISTS(
    SELECT 1 FROM article_reads ar WHERE ar.user_id = ?1 AND ar.article_id = a.id
  ) THEN 1 ELSE 0 END AS read
FROM articles a
JOIN feeds f ON f.source_feed_id = a.source_feed_id
WHERE f.user_id = ?2
  AND (?3 IS NULL OR f.id = ?4)
  AND (LOWER(a.title) LIKE '%' || LOWER(?5) || '%'
       OR LOWER(a.description) LIKE '%' || LOWER(?6) || '%')
ORDER BY a.pub_date DESC NULLS LAST, a.created_at DESC
LIMIT ?8 OFFSET ?7
`

type ListArticlesForUserBySmartFeedParams struct {
	ReaderID string      `json:"reader_id"`
	OwnerID  string      `json:"owner_id"`
	FeedID   interface{} `json:"feed_id"`
	FeedId2  string      `json:"feed_id2"`
	Query    string      `json:"query"`
	Query2   string      `json:"query2"`
	Offset   int64       `json:"offset"`
	Limit    int64       `json:"limit"`
}

type ListArticlesForUserBySmartFeedRow struct {
	ID           string  `json:"id"`
	Title        *string `json:"title"`
	Link         *string `json:"link"`
	Description  *string `json:"description"`
	Content      *string `json:"content"`
	ImageUrl     *string `json:"image_url"`
	PubDate      *string `json:"pub_date"`
	Guid         *string `json:"guid"`
	SourceFeedID *string `json:"source_feed_id"`
	CreatedAt    string  `json:"created_at"`
	Read         int64   `json:"read"`
}

func (q *Queries) ListArticlesForUserBySmartFeed(ctx context.Context, arg ListArticlesForUserBySmartFeedParams) ([]ListArticlesForUserBySmartFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesForUserBySmartFeed,
		arg.ReaderID,
		arg.OwnerID,
		arg.FeedID,
		arg.FeedId2,
		arg.Query,
		arg.Query2,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesForUserBySmartFeedRow
	for rows.Next() {
		var i ListArticlesForUserBySmartFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Link,
			&i.Description,
			&i.Content,
			&i.ImageUrl,
			&i.PubDate,
			&i.Guid,
			&i.SourceFeedID,
			&i.CreatedAt,
			&i.Read,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByUser = `-- name: ListCategoriesByUser :many
SELECT id, name, user_id, created_at FROM categories WHERE user_id = ? ORDER BY name ASC
`

func (q *Queries) ListCategoriesByUser(ctx context.Context, userID string) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingGuids = `-- name: ListExistingGuids :many
SELECT guid FROM articles WHERE source_feed_id = ? AND guid IS NOT NULL
`

func (q *Queries) ListExistingGuids(ctx context.Context, sourceFeedID *string) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, listExistingGuids, sourceFeedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var guid *string
		if err := rows.Scan(&guid); err != nil {
			return nil, err
		}
		items = append(items, guid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsByUser = `-- name: ListFeedsByUser :many
SELECT id, url, title, description, language, user_id, source_feed_id, category_id, last_fetched_at, created_at FROM feeds WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListFeedsByUser(ctx context.Context, userID string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Language,
			&i.UserID,
			&i.SourceFeedID,
			&i.CategoryID,
			&i.LastFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSmartFeedsByUser = `-- name: ListSmartFeedsByUser :many
SELECT id, name, "query", feed_id, user_id, created_at FROM smart_feeds WHERE user_id = ? ORDER BY name ASC
`

func (q *Queries) ListSmartFeedsByUser(ctx context.Context, userID string) ([]SmartFeed, error) {
	rows, err := q.db.QueryContext(ctx, listSmartFeedsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmartFeed
	for rows.Next() {
		var i SmartFeed
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Query,
			&i.FeedID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceFeedsToSync = `-- name: ListSourceFeedsToSync :many
SELECT id, url, title, description, language, last_fetched_at, created_at FROM source_feeds
WHERE last_fetched_at IS NULL OR last_fetched_at < datetime('now', ?)
`

func (q *Queries) ListSourceFeedsToSync(ctx context.Context, datetime interface{}) ([]SourceFeed, error) {
	rows, err := q.db.QueryContext(ctx, listSourceFeedsToSync, datetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceFeed
	for rows.Next() {
		var i SourceFeed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.Language,
			&i.LastFetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, role, banned, banned_reason, created_at
FROM users ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID           string  `json:"id"`
	Name         *string `json:"name"`
	Email        string  `json:"email"`
	Role         string  `json:"role"`
	Banned       int64   `json:"banned"`
	BannedReason *string `json:"banned_reason"`
	CreatedAt    string  `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Banned,
			&i.BannedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllReadForUser = `-- name: MarkAllReadForUser :exec
INSERT INTO article_reads (user_id, article_id)
SELECT ?, a.id FROM articles a
JOIN feeds f ON f.source_feed_id = a.source_feed_id
WHERE f.user_id = ?
ON CONFLICT(user_id, article_id) DO NOTHING
`

type MarkAllReadForUserParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

func (q *Queries) MarkAllReadForUser(ctx context.Context, arg MarkAllReadForUserParams) error {
	_, err := q.db.ExecContext(ctx, markAllReadForUser, arg.UserID, arg.UserID_2)
	return err
}

const markArticleRead = `-- name: MarkArticleRead :exec
INSERT INTO article_reads (user_id, article_id) VALUES (?, ?)
ON CONFLICT(user_id, article_id) DO NOTHING
`

type MarkArticleReadParams struct {
	UserID    string `json:"user_id"`
	ArticleID string `json:"article_id"`
}

func (q *Queries) MarkArticleRead(ctx context.Context, arg MarkArticleReadParams) error {
	_, err := q.db.ExecContext(ctx, markArticleRead, arg.UserID, arg.ArticleID)
	return err
}

const markArticleUnread = `-- name: MarkArticleUnread :exec
DELETE FROM article_reads WHERE user_id = ? AND article_id = ?
`

type MarkArticleUnreadParams struct {
	UserID    string `json:"user_id"`
	ArticleID string `json:"article_id"`
}

func (q *Queries) MarkArticleUnread(ctx context.Context, arg MarkArticleUnreadParams) error {
	_, err := q.db.ExecContext(ctx, markArticleUnread, arg.UserID, arg.ArticleID)
	return err
}

const renameCategory = `-- name: RenameCategory :exec
UPDATE categories SET name = ? WHERE id = ? AND user_id = ?
`

type RenameCategoryParams struct {
	Name   string `json:"name"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) error {
	_, err := q.db.ExecContext(ctx, renameCategory, arg.Name, arg.ID, arg.UserID)
	return err
}

const setFeedCategory = `-- name: SetFeedCategory :exec
UPDATE feeds SET category_id = ? WHERE id = ? AND user_id = ?
`

type SetFeedCategoryParams struct {
	CategoryID *string `json:"category_id"`
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
}

func (q *Queries) SetFeedCategory(ctx context.Context, arg SetFeedCategoryParams) error {
	_, err := q.db.ExecContext(ctx, setFeedCategory, arg.CategoryID, arg.ID, arg.UserID)
	return err
}

const setRateLimit = `-- name: SetRateLimit :exec
INSERT INTO rate_limit_entries (key, count, reset_at)
VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET count = excluded.count, reset_at = excluded.reset_at
`

type SetRateLimitParams struct {
	Key     string `json:"key"`
	Count   int64  `json:"count"`
	ResetAt string `json:"reset_at"`
}

func (q *Queries) SetRateLimit(ctx context.Context, arg SetRateLimitParams) error {
	_, err := q.db.ExecContext(ctx, setRateLimit, arg.Key, arg.Count, arg.ResetAt)
	return err
}

const setUserRoleBanned = `-- name: SetUserRoleBanned :exec
UPDATE users SET role = ?, banned = ?, banned_reason = ? WHERE id = ?
`

type SetUserRoleBannedParams struct {
	Role         string  `json:"role"`
	Banned       int64   `json:"banned"`
	BannedReason *string `json:"banned_reason"`
	ID           string  `json:"id"`
}

func (q *Queries) SetUserRoleBanned(ctx context.Context, arg SetUserRoleBannedParams) error {
	_, err := q.db.ExecContext(ctx, setUserRoleBanned,
		arg.Role,
		arg.Banned,
		arg.BannedReason,
		arg.ID,
	)
	return err
}

const updateSourceFeedMeta = `-- name: UpdateSourceFeedMeta :exec
UPDATE source_feeds
SET title = ?, description = ?, language = ?, last_fetched_at = datetime('now')
WHERE id = ?
`

type UpdateSourceFeedMetaParams struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Language    string  `json:"language"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateSourceFeedMeta(ctx context.Context, arg UpdateSourceFeedMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateSourceFeedMeta,
		arg.Title,
		arg.Description,
		arg.Language,
		arg.ID,
	)
	return err
}

const upsertCachedImage = `-- name: UpsertCachedImage :exec
INSERT INTO image_cache (source_url, content_type, data, fetched_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(source_url) DO UPDATE SET content_type = excluded.content_type, data = excluded.data, fetched_at = excluded.fetched_at
`

type UpsertCachedImageParams struct {
	SourceUrl   string `json:"source_url"`
	ContentType string `json:"content_type"`
	Data        []byte `json:"data"`
}

func (q *Queries) UpsertCachedImage(ctx context.Context, arg UpsertCachedImageParams) error {
	_, err := q.db.ExecContext(ctx, upsertCachedImage, arg.SourceUrl, arg.ContentType, arg.Data)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}

const upsertSourceFeed = `-- name: UpsertSourceFeed :one
INSERT INTO source_feeds (id, url, language)
VALUES (?, ?, ?)
ON CONFLICT(url) DO UPDATE SET language = excluded.language
RETURNING id, url, title, description, language, last_fetched_at, created_at
`

type UpsertSourceFeedParams struct {
	ID       string `json:"id"`
	Url      string `json:"url"`
	Language string `json:"language"`
}

func (q *Queries) UpsertSourceFeed(ctx context.Context, arg UpsertSourceFeedParams) (SourceFeed, error) {
	row := q.db.QueryRowContext(ctx, upsertSourceFeed, arg.ID, arg.Url, arg.Language)
	var i SourceFeed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.LastFetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserPreference = `-- name: UpsertUserPreference :exec
INSERT INTO user_preferences (
  user_id, theme, design, card_style, density, font_scale, accent_color,
  show_images, show_source, show_date, show_description, description_lines, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(user_id) DO UPDATE SET
  theme = excluded.theme, design = excluded.design, card_style = excluded.card_style,
  density = excluded.density, font_scale = excluded.font_scale, accent_color = excluded.accent_color,
  show_images = excluded.show_images, show_source = excluded.show_source, show_date = excluded.show_date,
  show_description = excluded.show_description, description_lines = excluded.description_lines,
  updated_at = datetime('now')
`

type UpsertUserPreferenceParams struct {
	UserID           string `json:"user_id"`
	Theme            string `json:"theme"`
	Design           string `json:"design"`
	CardStyle        string `json:"card_style"`
	Density          string `json:"density"`
	FontScale        string `json:"font_scale"`
	AccentColor      string `json:"accent_color"`
	ShowImages       int64  `json:"show_images"`
	ShowSource       int64  `json:"show_source"`
	ShowDate         int64  `json:"show_date"`
	ShowDescription  int64  `json:"show_description"`
	DescriptionLines int64  `json:"description_lines"`
}

func (q *Queries) UpsertUserPreference(ctx context.Context, arg UpsertUserPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPreference,
		arg.UserID,
		arg.Theme,
		arg.Design,
		arg.CardStyle,
		arg.Density,
		arg.FontScale,
		arg.AccentColor,
		arg.ShowImages,
		arg.ShowSource,
		arg.ShowDate,
		arg.ShowDescription,
		arg.DescriptionLines,
	)
	return err
}
